# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isImg', models.BooleanField(verbose_name='是否图片评论')),
                ('context', models.CharField(max_length=30, verbose_name='评论正文')),
            ],
        ),
        migrations.CreateModel(
            name='CommentImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=150, verbose_name='图片路径')),
                ('uploadtime', models.TimeField(verbose_name='上传时间')),
            ],
        ),
        migrations.CreateModel(
            name='WbImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=150, verbose_name='图片路径')),
                ('uploadtime', models.TimeField(verbose_name='上传时间')),
            ],
        ),
        migrations.CreateModel(
            name='Wblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200, verbose_name='微博正文')),
                ('sendtime', models.DateTimeField(verbose_name='发布时间')),
                ('goods', models.IntegerField(verbose_name='赞')),
            ],
            options={
                'ordering': ['-sendtime'],
            },
        ),
        migrations.AddField(
            model_name='wbimg',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.Wblog'),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.Wblog'),
        ),
    ]
